# @package _global_

algo:
  name: dpmd
  critic_hidden_dims: [256, 256]
  critic_lr: 0.0003
  discount: 0.99
  num_samples: 10
  ema: 0.005
  temp: 0.1
  q_clip: 3.0
  q_stats_lr: 0.0001
  diffusion:
    time_dim: 64
    mlp_hidden_dims: [256, 256]
    lr: 0.0003
    end_lr: null
    lr_decay_steps: null
    lr_decay_begin: null
    steps: 20
    clip_sampler: true
    x_min: -1.0
    x_max: 1.0
    solver: ddpm
