# @package _global_

algo:
  name: sdac
  critic_hidden_dims: [256, 256, 256]
  critic_lr: 0.0003
  alpha_lr: 0.0003
  target_entropy_scale: 1.0
  discount: 0.99
  num_samples: 32
  num_reverse_samples: 64
  ema: 0.005
  alpha: 1.0
  diffusion:
    time_dim: 64
    mlp_hidden_dims: [256, 256, 256]
    lr: 0.0001
    end_lr: null
    lr_decay_steps: null
    lr_decay_begin: null
    steps: 20
    noise_schedule: linear
    clip_sampler: true
    x_min: -1.0
    x_max: 1.0
    solver: ddpm
    noise_scaler: 1.0
