# @package _global_

algo:
  name: td7
  discount: 0.99
  hidden_dim: 256
  embed_dim: 256
  actor_lr: 0.0003
  critic_lr: 0.0003
  encoder_lr: 0.0003
  clip_grad_norm: null
  actor_update_freq: 2
  target_update_freq: 250
  target_policy_noise: 0.2
  noise_clip: 0.5
  exploration_noise: 0.1
  lam: 0.0
  max_action: 1.0

lap_alpha: 0.4
lap_reset_frames: 250
warmup_frames: 25000
random_frames: 25000
