defaults:
  - mujoco/config
  - mujoco/algo/ppo
  - _self_

# Override some defaults for PPO
task: HalfCheetah-v5
seed: 0

# PPO-specific configurations
rollout_steps: 2048
update_epochs: 10
num_iterations: 500  # 500 * 2048 = ~1M steps
normalize_advantages: true
gamma: 0.99
gae_lambda: 0.95
save_freq: 50

# Logging
log:
  dir: "./logs/ppo"
  tag: "default"
  project: "flowrl-ppo"
  entity: null
